language: erlang

os:
  - linux

otp_release:
   - 21.3

notifications:
  email: rtb-team+travis@adroll.com

script:
  - rebar3 --version
  - erl -version
  - rebar3 dialyzer || true # to generate the PLT :(
  - rebar3 test
